In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("datasets/movies_metadata.csv")
data=data.drop(["belongs_to_collection","homepage","genres","spoken_languages","poster_path"],axis='columns')
data

C:\Users\Sanket Kittad\AppData\Local\Temp\ipykernel_16412\2705082601.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("datasets/movies_metadata.csv")

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
0,False,30000000,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,Released,NaN,Toy Story,False,7.7,5415.0
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,0,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,0,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,0,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,0,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,Released,NaN,Queerama,False,0.0,0.0

In [4]:
data["original_language"].unique()

array(['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru',
       'sv', 'ja', 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy',
       'vi', 'cs', 'da', 'no', 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo',
       'ca', 'fi', 'th', 'sk', 'bs', 'hi', 'tr', 'is', 'ps', 'ab', 'eo',
       'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et', 'ku', 'fy', 'lv',
       'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk', 'ms',
       'sq', nan, '104.0', 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo',
       'ay', 'kn', 'eu', 'ne', 'pa', 'ky', 'gl', '68.0', 'uz', 'sm', 'mt',
       '82.0', 'hy', 'iu', 'lb', 'si'], dtype=object)

In [5]:
data.dropna()

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
5,False,60000000,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,187436818.0,170.0,Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45449,False,0,14885,tt0457437,en,Pooh's Heffalump Halloween Movie,"It's Halloween in the 100 Acre Wood, and Roo's...",2.568495,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2005-09-13,0.0,67.0,Released,Celebrate Lumpy's First Halloween.,Pooh's Heffalump Halloween Movie,False,5.4,7.0
45454,False,0,420346,tt4130180,en,The Morning After,The Morning After is a feature film that consi...,0.139936,"[{'name': 'Oops Doughnuts Productions', 'id': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-01-11,0.0,79.0,Released,What happened last night?,The Morning After,False,4.0,2.0
45456,False,0,84419,tt0038621,en,House of Horrors,An unsuccessful sculptor saves a madman named ...,0.222814,"[{'name': 'Universal Pictures', 'id': 33}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1946-03-29,0.0,65.0,Released,Meet...The CREEPER!,House of Horrors,False,6.3,8.0
45458,False,0,289923,tt0252966,en,The Burkittsville 7,A film archivist revisits the story of Rustin ...,0.38645,"[{'name': 'Neptune Salad Entertainment', 'id':...","[{'iso_3166_1': 'US', 'name': 'United States o...",2000-10-03,0.0,30.0,Released,"Do you know what happened 50 years before ""The...",The Burkittsville 7,False,7.0,1.0
45463,False,0,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,Released,A deadly game of wits.,Betrayal,False,3.8,6.0

In [6]:
data["original_language"].unique()

array(['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru',
       'sv', 'ja', 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy',
       'vi', 'cs', 'da', 'no', 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo',
       'ca', 'fi', 'th', 'sk', 'bs', 'hi', 'tr', 'is', 'ps', 'ab', 'eo',
       'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et', 'ku', 'fy', 'lv',
       'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk', 'ms',
       'sq', nan, '104.0', 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo',
       'ay', 'kn', 'eu', 'ne', 'pa', 'ky', 'gl', '68.0', 'uz', 'sm', 'mt',
       '82.0', 'hy', 'iu', 'lb', 'si'], dtype=object)

In [7]:
en=data[data["original_language"]=='en']
fr=data[data["original_language"]=='fr']
en

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
0,False,30000000,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,Released,NaN,Toy Story,False,7.7,5415.0
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45459,False,0,222848,tt0112613,en,Caged Heat 3000,It's the year 3000 AD. The world's most danger...,0.661558,"[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-01-01,0.0,85.0,Released,NaN,Caged Heat 3000,False,3.5,1.0
45460,False,0,30840,tt0102797,en,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,0.0,104.0,Released,NaN,Robin Hood,False,5.7,26.0
45463,False,0,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,0,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,0,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,Released,NaN,Queerama,False,0.0,0.0

In [8]:
fr

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
28,False,18000000,902,tt0112682,fr,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.822423,"[{'name': 'Procirep', 'id': 311}, {'name': 'Co...","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1995-05-16,1738611.0,108.0,Released,Where happily ever after is just a dream.,The City of Lost Children,False,7.6,308.0
32,False,0,78802,tt0114952,fr,"Guillaumet, les ailes du courage",NaN,0.745542,"[{'name': 'Iwerks Entertainment', 'id': 70801}]","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",1996-09-18,0.0,50.0,Released,NaN,Wings of Courage,False,6.8,4.0
58,False,0,99040,tt0112714,fr,Le confessionnal,"The year is 1952, in Quebec City. Rachel (16),...",0.120789,[],"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",1995-09-29,0.0,100.0,Released,NaN,The Confessional,False,6.5,2.0
67,False,0,4482,tt0113149,fr,Gazon maudit,"After learning of her husband's infidelities, ...",2.518051,"[{'name': 'Renn Productions', 'id': 82}, {'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}]",1995-02-08,0.0,95.0,Released,NaN,French Twist,False,6.0,43.0
72,False,0,48750,tt0113828,fr,Les misérables,"In France during World War II, a poor and illi...",1.479446,"[{'name': 'Les Films 13', 'id': 1742}, {'name'...","[{'iso_3166_1': 'FR', 'name': 'France'}]",1995-03-22,0.0,175.0,Released,"In a time of chaos, in a world of change, he w...",Les Miserables,False,6.6,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45444,False,0,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,"[{'name': 'Star-Film', 'id': 7159}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1905-01-01,0.0,3.0,Released,NaN,The Living Playing Cards,False,6.1,8.0
45447,False,0,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1904-03-05,0.0,3.0,Released,NaN,The Untameable Whiskers,False,6.0,6.0
45448,False,0,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1904-01-01,0.0,2.0,Released,NaN,The Imperceptable Transmutations,False,5.0,2.0
45450,False,0,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1900-01-01,0.0,1.0,Released,NaN,The One-Man Band,False,6.5,22.0
45451,False,0,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,"[{'name': 'Star-Film', 'id': 7159}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1900-01-01,0.0,2.0,Released,NaN,The Fat and Lean Wrestling Match,False,6.5,6.0

In [9]:
merged_data=pd.concat([en,fr])
merged_data

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
0,False,30000000,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,Released,NaN,Toy Story,False,7.7,5415.0
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45444,False,0,44333,tt0135179,fr,Les cartes vivantes,A bearded magician holds up a large playing ca...,0.208349,"[{'name': 'Star-Film', 'id': 7159}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1905-01-01,0.0,3.0,Released,NaN,The Living Playing Cards,False,6.1,8.0
45447,False,0,44324,tt0135631,fr,Le Roi du maquillage,The background of this picture represents a sc...,0.213973,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1904-03-05,0.0,3.0,Released,NaN,The Untameable Whiskers,False,6.0,6.0
45448,False,0,122036,tt0224286,fr,Les Transmutations imperceptibles,This shows a prince entering upon the stage of...,0.071782,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1904-01-01,0.0,2.0,Released,NaN,The Imperceptable Transmutations,False,5.0,2.0
45450,False,0,49280,tt0135453,fr,L'Homme orchestre,A band-leader has arranged seven chairs for th...,1.109068,"[{'name': 'Star Film Company', 'id': 45867}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1900-01-01,0.0,1.0,Released,NaN,The One-Man Band,False,6.5,22.0
45451,False,0,106807,tt0135571,fr,Nouvelles luttes extravagantes,A series of fantastical wrestling matches.,0.225432,"[{'name': 'Star-Film', 'id': 7159}]","[{'iso_3166_1': 'FR', 'name': 'France'}]",1900-01-01,0.0,2.0,Released,NaN,The Fat and Lean Wrestling Match,False,6.5,6.0

In [10]:
data

,adult,budget,id,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,video,vote_average,vote_count
0,False,30000000,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,Released,NaN,Toy Story,False,7.7,5415.0
1,False,65000000,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,0,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,16000000,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,0,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,0.072051,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,0,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,0,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,0,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,0,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,Released,NaN,Queerama,False,0.0,0.0

In [11]:
melted_data=data.melt(id_vars=["id","original_title"],value_vars=["revenue","budget"],value_name="money_metrics",var_name="value")
melted_data

           id               original_title    value money_metrics
0         862                    Toy Story  revenue   373554033.0
1        8844                      Jumanji  revenue   262797249.0
2       15602             Grumpier Old Men  revenue           0.0
3       31357            Waiting to Exhale  revenue    81452156.0
4       11862  Father of the Bride Part II  revenue    76578911.0
...       ...                          ...      ...           ...
90927  439050                      رگ خواب   budget             0
90928  111109          Siglo ng Pagluluwal   budget             0
90929   67758                     Betrayal   budget             0
90930  227506          Satana likuyushchiy   budget             0
90931  461257                     Queerama   budget             0

[90932 rows x 4 columns]

In [12]:
data["index"]=range(1,len(data)+1)
wide_data=data.pivot_table(index=['index','id','title'],values=["revenue","budget"])
wide_data

                                              budget      revenue
index id     title
1     862    Toy Story                    30000000.0  373554033.0
2     8844   Jumanji                      65000000.0  262797249.0
3     15602  Grumpier Old Men                    0.0          0.0
4     31357  Waiting to Exhale            16000000.0   81452156.0
5     11862  Father of the Bride Part II         0.0   76578911.0
...                                              ...          ...
45462 439050 Subdue                              0.0          0.0
45463 111109 Century of Birthing                 0.0          0.0
45464 67758  Betrayal                            0.0          0.0
45465 227506 Satan Triumphant                    0.0          0.0
45466 461257 Queerama                            0.0          0.0

[45460 rows x 2 columns]